# Generated by Django 3.2.5 on 2021-07-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_text', models.CharField(max_length=50)),
                ('back_text', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('private', models.BooleanField()),
                ('user', models.PositiveSmallIntegerField()),
                ('likes', models.PositiveIntegerField()),
            ],
        ),
    ]
